### ISSUE TITLE
Doing jointeam on the bot causes it to crash

### ISSUE THREAD

**Issue by Standard8** [mozilla/standup-irc#31]
I tried this on irc.mozilla.org with private conversation, doing !jointeam <team name> (without the < >) crashed the bot.

**Comment by willkg** [comment]
We're in the process of doing a standup v2 rewrite. Between when this issue was written and roughly a month ago, this project was essentially unmaintained.

Standup v2 doesn't let you do team management via the irc bot. That'll all get done in the web app, though we haven't implemented those bits, yet, so for now it'll require admin help.

See https://wiki.mozilla.org/Standup for up-to-date help there.

Given that, I'm closing this out.
