### ISSUE TITLE
Trying to create a team crashes the bot

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/standup-irc#35]
I tried to !mkteam a new team in irc.mozilla.org and bot keeps crashing.

**Comment by mozfreddyb** [comment]
The command `!mkteam` does not exist anymore. Sorry for the long time to reply.
Please continue filing bugs if you see problems.

**Comment by willkg** [comment]
We're in the process of doing a standup v2 rewrite. Between when this issue was written and roughly a month ago, this project was essentially unmaintained.

Standup v2 doesn't let you do team management via the irc bot. That'll all get done in the web app, though we haven't implemented those bits, yet, so for now it'll require admin help.

See https://wiki.mozilla.org/Standup for up-to-date help there. Given that, I'm closing this out.
